### ISSUE TITLE
`sam deploy` commands return an error

### ISSUE THREAD

**Issue by ken5scal** [aws-samples/lambdaedge-openidconnect-samples#9]
I have tried the following command got an error.

* command 
```
$ sam deploy \
            --template-file build/packaged.yaml \
            --stack-name oidc-auth \
            --capabilities CAPABILITY_NAMED_IAM \
			--parameter-overrides BucketName=${YOUR_NEW_STATIC_SITE_BUCKET_NAME} LogBucketName=${YOUR_LOG_BUCKET_NAME} SecretKeyName=${YOUR_SECRETS_MANAGER_KEY_NAME}
```

* Expected: Change set is created
* Actual: returned following error (with debug option)

```
Telemetry endpoint configured to be https://aws-serverless-tools-telemetry.us-west-2.amazonaws.com/metrics

        Deploying with following values
        ===============================
        Stack name                 : oidc-auth
        Region                     : None
        Confirm changeset          : False
        Deployment s3 bucket       : None
        Capabilities               : ["CAPABILITY_NAMED_IAM"]
        Parameter overrides        : {'BucketName': 'xxx', 'SecretKeyName': 'test_oidc_conf', 'LogBucketName': 'yyy'}

Initiating deployment
=====================
Property CodeUri of CloudFrontAuthFunction is already a S3 URL
Collected default values for parameters: {'MinimumTLSVersion': 'TLSv1.2_2018'}
Unable to resolve property CanonicalUser: OrderedDict([('Fn::GetAtt', ['CloudFrontOriginAccessIdentity', 'S3CanonicalUserId'])]). Leaving as is.
Unable to resolve property Bucket: OrderedDict([('Fn::GetAtt', ['LogBucketName', 'DomainName'])]). Leaving as is.
Unable to resolve property DomainName: OrderedDict([('Fn::GetAtt', ['S3Bucket', 'DomainName'])]). Leaving as is.
6 resources found in the template
Found Serverless function with name='CloudFrontAuthFunction' and CodeUri='.'

Waiting for changeset to be created..
Sending Telemetry: {'metrics': [{'commandRun': {'awsProfileProvided': False, 'debugFlagProvided': True, 'region': '', 'commandName': 'sam deploy', 'duration': 6070, 'exitReason': 'ChangeSetError', 'exitCode': 1, 'requestId': 'xxx', 'installationId': 'xxx', 'sessionId': 'xxx', 'executionEnvironment': 'CLI', 'pyversion': '3.7.8', 'samcliVersion': '0.53.0'}}]}
HTTPSConnectionPool(host='aws-serverless-tools-telemetry.us-west-2.amazonaws.com', port=443): Read timed out. (read timeout=0.1)
Error: Failed to create changeset for the stack: oidc-auth, ex: Waiter ChangeSetCreateComplete failed: Waiter encountered a terminal failure state Status: FAILED. Reason: Template error: instance of Fn::GetAtt references undefined resource LogBucketName
```

**Comment by noyceguy** [comment]
Hi @ken5scal, can you try to upgrade your SAM CLI version to the latest and let me know if you still are encountering the error above?

**Comment by KenjiFukudome** [comment]
Hi There

@ajrice6713 

I am also seeing an same error on the deploy command.

```
$ sam deploy \
   --template-file build/packaged.yaml \
   --stack-name oidc-auth \
   --capabilities CAPABILITY_NAMED_IAM \
   --parameter-overrides ParameterKey=BucketName,ParameterValue=${STATIC_WEBSITE_BUCKET} ParameterKey=LogBucketName,ParameterValue=${YOUR_LOG_BUCKET_NAME} ParameterKey=SecretKeyName,ParameterValue=${YOUR_SECRETS_MANAGER_KEY_NAME}

        Deploying with following values
        ===============================
        Stack name                   : oidc-auth
        Region                       : None
        Confirm changeset            : False
        Disable rollback             : False
        Deployment s3 bucket         : None
        Capabilities                 : ["CAPABILITY_NAMED_IAM"]
        Parameter overrides          : {"BucketName": "xxx "LogBucketName": "xxx", "SecretKeyName": "xxx"}
        Signing Profiles             : {}

Initiating deployment
_=====================_

Waiting for changeset to be created..
Error: Failed to create changeset for the stack: oidc-auth, ex: Waiter ChangeSetCreateComplete failed: Waiter encountered a terminal failure state: For expression "Status" we matched expected path: "FAILED" Status: FAILED. Reason: Template error: instance of Fn::GetAttreferences undefined resource LogBucketName
```

If already you got fixed the problem, could you please tell me that?
Thank you for your support.

Using SAM CLI, Version 1.35.0

Regards,
Kenji

**Comment by ajrice6713** [comment]
Hey @KenjiFukudome 

I could not get around the deploy issue and ended up finding a [different project](https://github.com/Widen/cloudfront-auth) to implement okta auth (in front of a docusaurus site)

I had some issues with this one as well and opened an issue but was eventually able to get it working successfully 

https://github.com/Widen/cloudfront-auth/issues/95

Its very important that the config is setup correctly and that the Lambda@Edge is configured to trigger on the viewer request for everything to work properly.

**Comment by KenjiFukudome** [comment]
Hi @ajrice6713

Thank you for your reply.

I have avoided the error of "sam deploy", so I'll share it.
However, it is still in the process of okta certification.

Step1:
Please add LogBucketDomainName Parameter to "LogBucketDomainName\template.yaml" file as below.
<Before>
```
    LogBucketName:
          Type: String
          Description: The name of the Log Content S3 Bucket already existing
    SecretKeyName:
        Type: String
        Description: The name of the Secret in Secrets manager for the OIDC configuaration (e.g. okta-configuration-v4cw9Z)
```

<After>
```
    LogBucketName:
          Type: String
          Description: The name of the Log Content S3 Bucket already existing
    LogBucketDomainName:
          Type: String
          Description: The Domain name of the Log Content S3 Bucket already existing
    SecretKeyName:
        Type: String
        Description: The name of the Secret in Secrets manager for the OIDC configuaration (e.g. okta-configuration-v4cw9Z)
```

**Comment by KenjiFukudome** [comment]
Hi @ajrice6713

Thank you for your reply!

I have avoided the error of "sam deploy", so I'll share it.
(However, now, it is still in the process of okta certification.)

Step1:
Please add LogBucketDomainName Parameter to "LogBucketDomainName\template.yaml" file as below.

[Before]
```
    LogBucketName:
          Type: String
          Description: The name of the Log Content S3 Bucket already existing
    SecretKeyName:
        Type: String
        Description: The name of the Secret in Secrets manager for the OIDC configuaration (e.g. okta-configuration-v4cw9Z)
```
[After]
```
    LogBucketName:
          Type: String
          Description: The name of the Log Content S3 Bucket already existing
    LogBucketDomainName:
          Type: String
          Description: The Domain name of the Log Content S3 Bucket already existing
    SecretKeyName:
        Type: String
        Description: The name of the Secret in Secrets manager for the OIDC configuaration (e.g. okta-configuration-v4cw9Z)
```

Step2:
Please change Node.js version from 10 to 14 in "LogBucketDomainName\template.yaml" file as below.
[Before]
```
          Role: !GetAtt LambdaEdgeFunctionRole.Arn
          Runtime: nodejs10.x
          Handler: auth.handle
```
[After]
```
          Role: !GetAtt LambdaEdgeFunctionRole.Arn
          Runtime: nodejs14.x
          Handler: auth.handle
```

Step3:
After step1 and step2, 
please add following setting to a terminal and run the following "sam deploy" command that added LogBucketDomainName key.

$ export YOUR_LOG_BUCKET_DOMAIN_NAME=${YOUR_LOG_BUCKET_NAME}.s3.amazon.aws.com
$ sam build -b ./build -s . -t template.yaml -u
$ sam package --template-file build/template.yaml --s3-bucket ${DEPLOY_BUCKET} --output-template-file build/packaged.yaml
$ sam deploy \
  --template-file build/packaged.yaml \
  --stack-name oidc-auth \
  --capabilities CAPABILITY_NAMED_IAM 
  --parameter-overrides ParameterKey=BucketName,ParameterValue=${STATIC_WEBSITE_BUCKET} ParameterKey=LogBucketName,ParameterValue=${YOUR_LOG_BUCKET_NAME} ParameterKey=SecretKeyName,ParameterValue=${YOUR_SECRETS_MANAGER_KEY_NAME} ParameterKey=LogBucketDomainName,ParameterValue=${YOUR_LOG_BUCKET_DOMAIN_NAME}

Finally:
From Step1 to Step3, "sam deploy" is successed.

Regards,
@KenjiFukudome
